version: "3"

services:
  pg:
    container_name: pg
    image: postgres:latest
    restart: always
    ports: 
      - 5432:5432
    volumes: 
      - ./postgresql/data:/var/lib/postgresql/data
      - ./postgresql/initdb:/docker-entrypoint-initdb.d
    environment: 
      POSTGRES_USER: admin 
      POSTGRES_PASSWORD: password 
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
      POSTGRES_DB: sqlx_db
      TZ: Asia/Tokyo
    hostname: pg 
    restart: always
    user: root

  pgadmin4:
    container_name: pgadmin4
    image: dpage/pgadmin4
    container_name: pgadmin4
    ports: 
      - 8000:80
    volumes: 
      - ./pgadmin4:/var/lib/pgadmin
    environment: 
      PGADMIN_DEFAULT_EMAIL: pg@admin.sql
      PGADMIN_DEFAULT_PASSWORD: password
    hostname: pgadmin4
    depends_on: 
      - pg
    restart: always


  app:
    build: .
    tty: true 
    volumes:
      - .:/go/src/app 